ecommerceproject/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Define your URL patterns here
    # Example: path('cart/', views.cart_view, name='cart'),
]

ecommerceproject/ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),  # This is the root URL pattern
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
    path('search/', views.SearchResult, name='search'),  # Example URL pattern for search page
    path('search-results/', views.SearchResult, name='search_results'),
]

ecommerceproject/shop/urls.py

from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),

]


ecommerceproject/cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return  self.product.price * self.quantity

    def __str__(self):
        return (self.product)

ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=250, blank=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)  # Added description field here

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', kwargs={'c_slug': self.slug})

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)

    def get_url(self):
        return reverse('shop:prodCatdetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return self.name

ecommerceproject/cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect

from  .models import Cart,CartItem
from shop.models import Product
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart = Cart.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


ecommerceproject/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request, 'search.html', {'query': query, 'products': products})







ecommerceproject/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def index(request):
    return HttpResponse("hey am here")
def allProdCat(request, c_slug=None):
    c_page = None
    products_list=None
    if c_slug!= None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)  # Use the correct variable name
    else:
        products_list = Product.objects.all().filter(available=True)
        paginator=Paginator(products_list,6)
        try:
            page=int(request.GET.get('page','1'))
        except:
            page=1
        try:
                products=paginator.page(page)
        except (EmptyPage,InvalidPage):
            products=paginator.page(paginator.num_pages)



    return render(request, "category.html", {'category': c_page, 'products': products})


def proDetail(request, c_slug, product_slug):
    try:
        product = get_object_or_404(Product, category__slug=c_slug, slug=product_slug)
    except Exception as e:
        # Handle the case where the product doesn't exist
        return HttpResponse("Product not found", status=404)
    return render(request, 'product.html', {'product': product})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/2aaafe3c84.js" crossorigin="anonymous"></script>
    <link  href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static popper.min.js %}" ></script>
<script src="{% static bootstrap.min.js %}" ></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
This is the cart page.Proceed to review your items and place the order

{% endblock %}
{% blocktitle %}
  Cart-ABC company pvt ltd
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center ">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart is empty

        </h1>
        <br>
        <p class="text-center">
            Please Click<a href="{% url 'shop:allProdCat' %}">Here</a>to continue shopping

        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
    Your Shopping Cart

        </h1>
        <br>

    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>

            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            </tbody>
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
                </td>
                <td class ="text-lef">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item_product.id}}
                    <br>
                    Price:$ {{cart_item.product.price }}
                    <br>
                    Qty: {{ cart_item.quantity}} x $ {{cart_item}}

                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product %}"></a>
                </td>
            </tr>
        </table>


    </div>

</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to ABC store where you can buy different items
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} - ABC store
    {% else %}
        See our new collections - ABC store
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div class="container">
            <div class="row my_row_class">
                <div class="col mx-auto">
                    <p><a href="{% url 'shop:allProdCat' %}">Our Product Collections</a></p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row my_row_class">
                <div class="col mx-auto">
                    <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}" style="height: 500px; width: 500px;">
                </div>
            </div>
        </div>
        <br>
        <div class="container">
            <h1 class="text-center my_title">{{ category.name }}</h1>
            <p class="text-justify">{{ category.description }}</p>
        </div>
    {% else %}
        <div class="container">
            <img class="my_image my_image_padding" src="{% static 'img/banner(1).jpg' %}" alt="Our Products" width="100%;">
        </div>
        <br>
        <div class="container">
            <h1 class="text-center my_title">Our Products Collections</h1>
            <p class="text-justify">Welcome to our online shop, where you'll find a wide range of stationery essentials to fuel your creativity and productivity. Whether you're jotting down notes, sketching ideas, or organizing your thoughts, we have everything you need. Explore our collection of premium pens, perfect for smooth writing experiences and elegant designs. Need something more versatile? Check out our selection of high-quality pencils, ideal for sketching, drafting, or shading. Keep your thoughts organized with our stylish diaries and notebooks, available in various sizes and designs to suit your style. And don't forget to grab a reliable eraser to correct any mistakes effortlessly. Shop now and elevate your stationery game with us!</p>
        </div>
    {% endif %}

    <div class="container">
        <div class="row mx-auto">
            {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center">
                        {% if product.image %}
                            <a href="{{ product.get_url }}">
                                <img src="{{ product.image.url }}" alt="{{ product.name }}" style="height: 200px; width: 200px;">
                            </a>
                        {% endif %}
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.price }}</p> <!-- Consider formatting the price -->
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if products.number == pg %} active{% endif %}">{{ pg }}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center" >&copy; ABC tech pvt ltd.All rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href ="{% url 'shop:allProdCat' %}"></a><img src="{% static 'img/logo.jpg' %}" alt="logimg" width="130px" height="130px">
    </center>
</header>

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">shop</a>
      </li>


      <li class="nav-item dropdown {% if 'shop in request.path' %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
            {% for cat in links %}
          <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a>
            {% endfor %}

        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="#"><i class="fas fa-shopping-cart"></i></a>
      </li>
    </ul>
    <form class="d-flex" action="{% url 'search_app:search_results' %}" method="get">
    {% csrf_token %}
    <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
</form>

  </div>
</nav>




ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

         {{ product.description|truncatewords:155 }}

{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }} - ABC store

    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p> <a href="{% url  'shop:allProdCat' %}">Home</a> | <a href ="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container"></div>
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <div>
    <img src="{{ product.image.url }}" alt="{{ product.name }}" style="height: 500px; width: 500px;">
</div>

        </div>
    </div>
</div>
<div>
    <div class="col-12 cil-sm-12 col-md-12 col-lg-6">
        <div>
        <h1 class="my_prod_title">{{product.name}}</h1>
        <p>${{product.price}}</p>
        <p class="my_title">Product Description</p>
        <p class="text-justify my_prod_text">{{product.description}}</p>
        {% if product.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>Out of stock</b></p>
        {% else %}
        <a class="btn btn-secondary" href=" ">Add to cart"</a>
        {% endif %}
    </div>
        </div>
</div>
</div>

{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
We have a variety of stationary items.
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: <b>"{{ query }}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center">
                {% if product.image %}
                <a href="{{ product.get_url }}">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" style="height: 200px; width: 200px;">
                </a>
                {% endif %}
                <div class="card-body">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.price }}</p> <!-- Consider formatting the price -->
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}